# Generated by Django 6.0.6 on 2026-07-05 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome da empresa')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_cliente', to=settings.AUTH_USER_MODEL, verbose_name='usuario responsavel')),
            ],
            options={
                'verbose_name': 'empresa cliente',
                'verbose_name_plural': 'empresas clientes',
                'ordering': ['nome'],
            },
        ),
    ]
