# Generated by Django 6.0.6 on 2026-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=180, verbose_name='endereco'),
        ),
        migrations.AddField(
            model_name='empresacliente',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=120, verbose_name='horario de funcionamento'),
        ),
        migrations.AddField(
            model_name='empresacliente',
            name='mensagem_inicial',
            field=models.TextField(blank=True, verbose_name='mensagem inicial'),
        ),
        migrations.AddField(
            model_name='empresacliente',
            name='nome_dono',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome do dono'),
        ),
        migrations.AddField(
            model_name='empresacliente',
            name='segmento',
            field=models.CharField(choices=[('estacionamento', 'Estacionamento'), ('clinica', 'Clinica'), ('advocacia', 'Advocacia'), ('contabilidade', 'Contabilidade'), ('assistencia', 'Assistencia tecnica'), ('comercio', 'Pequeno comercio')], default='estacionamento', max_length=30, verbose_name='segmento'),
        ),
        migrations.AddField(
            model_name='empresacliente',
            name='whatsapp_dono',
            field=models.CharField(blank=True, max_length=13, verbose_name='WhatsApp do dono'),
        ),
    ]
