# Generated by Django 6.0.6 on 2026-07-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresacliente_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saudacao', models.CharField(max_length=180, verbose_name='saudacao automatica')),
                ('pergunta_menu', models.CharField(max_length=180, verbose_name='pergunta do menu')),
                ('pergunta_dados', models.CharField(max_length=180, verbose_name='pergunta de coleta de dados')),
                ('pergunta_finalizacao', models.CharField(max_length=180, verbose_name='pergunta de finalizacao')),
                ('opcoes', models.JSONField(default=list, verbose_name='opcoes do menu')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_atendimento', to='core.empresacliente', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'fluxo de atendimento',
                'verbose_name_plural': 'fluxos de atendimento',
            },
        ),
    ]
