# Generated by Django 6.0.6 on 2026-07-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fluxoatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacliente',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='slug publico'),
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=120, verbose_name='nome do cliente')),
                ('telefone_cliente', models.CharField(max_length=13, verbose_name='telefone do cliente')),
                ('opcao_escolhida', models.CharField(max_length=120, verbose_name='opcao escolhida')),
                ('necessidade', models.CharField(max_length=180, verbose_name='necessidade')),
                ('observacao', models.TextField(blank=True, verbose_name='observacao')),
                ('status', models.CharField(default='novo', max_length=30, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.empresacliente', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'atendimento',
                'verbose_name_plural': 'atendimentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
