# Generated by Django 6.0.6 on 2026-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresacliente_public_slug_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado')], default='novo', max_length=30, verbose_name='status'),
        ),
    ]
