# Generated by Django 6.0.6 on 2026-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_atendimento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='avisado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='avisado em'),
        ),
    ]
