# Generated by Django 6.0.6 on 2026-07-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atendimento_avisado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Phone Number ID')),
                ('whatsapp_business_account_id', models.CharField(max_length=64, verbose_name='WhatsApp Business Account ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('last_communication_at', models.DateTimeField(blank=True, null=True, verbose_name='última comunicação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_integration', to='core.empresacliente', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'integração do WhatsApp',
                'verbose_name_plural': 'integrações do WhatsApp',
                'ordering': ['company__nome'],
                'constraints': [models.CheckConstraint(condition=models.Q(('phone_number_id', ''), _negated=True), name='whatsapp_phone_number_id_not_empty'), models.CheckConstraint(condition=models.Q(('whatsapp_business_account_id', ''), _negated=True), name='whatsapp_waba_id_not_empty')],
            },
        ),
    ]
