# Generated by Django 6.0.6 on 2026-07-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_whatsappintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(max_length=32, verbose_name='número WhatsApp')),
                ('nome', models.CharField(blank=True, max_length=120, verbose_name='nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.empresacliente')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ['nome', 'whatsapp_id'],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='core.contato'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_message_id', models.CharField(max_length=255, unique=True, verbose_name='ID externo da mensagem')),
                ('direcao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='direção')),
                ('tipo', models.CharField(default='unknown', max_length=32, verbose_name='tipo')),
                ('texto', models.TextField(blank=True, verbose_name='texto')),
                ('timestamp_meta', models.DateTimeField(blank=True, null=True, verbose_name='horário na Meta')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.atendimento')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='core.contato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.empresacliente')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['-timestamp_meta', '-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='contato',
            constraint=models.UniqueConstraint(fields=('empresa', 'whatsapp_id'), name='unique_contact_per_company_whatsapp'),
        ),
        migrations.AddConstraint(
            model_name='contato',
            constraint=models.CheckConstraint(condition=models.Q(('whatsapp_id', ''), _negated=True), name='contact_whatsapp_id_not_empty'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['empresa', 'atendimento', '-criado_em'], name='core_mensag_empresa_558aba_idx'),
        ),
    ]
