# Generated by Django 6.0.6 on 2026-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contato_atendimento_contato_mensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='automation_enabled',
            field=models.BooleanField(default=True, verbose_name='automação ativa'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='erro_codigo',
            field=models.CharField(blank=True, max_length=32, verbose_name='código de erro'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='status',
            field=models.CharField(choices=[('received', 'Recebida'), ('accepted', 'Aceita pela Meta'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='received', max_length=16, verbose_name='status'),
        ),
    ]
