# Generated by Django 6.0.6 on 2026-07-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_atendimento_automation_enabled_mensagem_erro_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='current_step',
            field=models.CharField(choices=[('MENU', 'Menu'), ('SERVICE', 'Escolha do serviço'), ('DATE', 'Escolha da data'), ('TIME', 'Escolha do horário'), ('CONFIRMATION', 'Confirmação'), ('WAITING_HUMAN', 'Aguardando atendente'), ('HUMAN', 'Em atendimento humano'), ('FINISHED', 'Finalizado')], default='MENU', max_length=24, verbose_name='etapa atual'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='flow_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='contexto da conversa'),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.empresacliente')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Concluído')], default='PENDING', max_length=16)),
                ('origem', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('MANUAL', 'Manual')], default='MANUAL', max_length=16)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='core.atendimento')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.contato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.empresacliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.servico')),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_agenda', to='core.empresacliente')),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('hora_fim__isnull', True), ('hora_inicio__isnull', True)), models.Q(('hora_fim__gt', models.F('hora_inicio')), ('hora_fim__isnull', False), ('hora_inicio__isnull', False)), _connector='OR'), name='block_times_both_null_or_valid')],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('intervalo_minutos', models.PositiveIntegerField(default=30)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='core.empresacliente')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='availability_end_after_start'), models.CheckConstraint(condition=models.Q(('intervalo_minutos__gt', 0)), name='availability_interval_positive'), models.UniqueConstraint(fields=('empresa', 'dia_semana', 'hora_inicio', 'hora_fim'), name='unique_availability_window')],
            },
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_service_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_minutos__gt', 0)), name='service_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['empresa', 'data', 'status'], name='core_agenda_empresa_b8d3fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('empresa', 'data', 'hora_inicio'), name='unique_active_appointment_start'),
        ),
    ]
