# Generated by Django 6.0.6 on 2026-07-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_atendimento_current_step_atendimento_flow_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegration',
            name='access_token_encrypted',
            field=models.TextField(blank=True, editable=False, verbose_name='token criptografado'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='conectada em'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='desconectada em'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='display_phone_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='número exibido'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='último código de erro'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='onboarding_status',
            field=models.CharField(choices=[('LEGACY', 'Configuração manual'), ('CONNECTED', 'Conectado'), ('ERROR', 'Erro de conexão'), ('EXPIRED', 'Token expirado'), ('DISCONNECTED', 'Desconectado')], default='LEGACY', max_length=20, verbose_name='status do onboarding'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='token expira em'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='verified_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome verificado'),
        ),
    ]
