# Generated by Django 6.0.6 on 2026-07-29 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ratelimitbucket_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='IA ativa')),
                ('assistant_name', models.CharField(default='Assistente', max_length=80, verbose_name='nome do assistente')),
                ('greeting', models.CharField(blank=True, max_length=300, verbose_name='mensagem inicial')),
                ('tone', models.CharField(default='cordial e objetivo', max_length=120, verbose_name='tom de atendimento')),
                ('business_description', models.TextField(blank=True, verbose_name='descrição do estabelecimento')),
                ('additional_information', models.TextField(blank=True, verbose_name='informações adicionais')),
                ('human_handoff_rules', models.TextField(blank=True, default='Quando o cliente solicitar uma pessoa ou o assunto estiver fora do escopo.', verbose_name='quando transferir para humano')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configuration', to='core.empresacliente')),
            ],
            options={
                'verbose_name': 'configuração de IA',
                'verbose_name_plural': 'configurações de IA',
            },
        ),
    ]
