# Generated by Django 6.0.6 on 2026-07-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='conversation_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='estado estruturado da conversa'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='conversation_summary',
            field=models.TextField(blank=True, verbose_name='resumo da conversa'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='summarized_message_count',
            field=models.PositiveIntegerField(default=0, verbose_name='mensagens incluídas no resumo'),
        ),
    ]
