# Generated by Django 6.0.6 on 2026-07-29 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_atendimento_conversation_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='assumido em'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_attendances', to=settings.AUTH_USER_MODEL, verbose_name='responsável atual'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finalizado em'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_attendances', to=settings.AUTH_USER_MODEL, verbose_name='finalizado por'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='handoff_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='motivo da transferência'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='última mensagem em'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to=settings.AUTH_USER_MODEL, verbose_name='enviada por'),
        ),
    ]
