# Generated by Django 6.0.6 on 2026-07-29 19:23

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_atendimento_assigned_at_atendimento_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(unique=True)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('stripe_price_id', models.CharField(blank=True, max_length=120)),
                ('operator_limit', models.PositiveIntegerField(default=1)),
                ('attendance_limit', models.PositiveIntegerField(default=100)),
                ('message_limit', models.PositiveIntegerField(default=1000)),
                ('ai_call_limit', models.PositiveIntegerField(default=500)),
                ('whatsapp_limit', models.PositiveIntegerField(default=1)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('RECEPTIONIST', 'Recepcionista'), ('AGENT', 'Atendente')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.empresacliente')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_completed', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='core.empresacliente')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='brl', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='core.empresacliente')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('offsets_hours', models.JSONField(default=core.models.default_reminder_offsets)),
                ('template_name', models.CharField(default='lembrete_agendamento', max_length=120)),
                ('language_code', models.CharField(default='pt_BR', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_configuration', to='core.empresacliente')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Período de teste'), ('ACTIVE', 'Ativa'), ('PAST_DUE', 'Pagamento pendente'), ('SUSPENDED', 'Suspensa'), ('CANCELED', 'Cancelada')], default='TRIAL', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.empresacliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_hours', models.PositiveIntegerField()),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('FAILED', 'Falhou')], default='PENDING', max_length=16)),
                ('external_message_id', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.agendamento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment', 'offset_hours'), name='unique_appointment_reminder')],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('RECEPTIONIST', 'Recepcionista'), ('AGENT', 'Atendente')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.empresacliente')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'user'), name='unique_company_membership')],
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('attendances', models.PositiveIntegerField(default=0)),
                ('messages', models.PositiveIntegerField(default=0)),
                ('ai_calls', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='core.empresacliente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'period'), name='unique_usage_period')],
            },
        ),
    ]
