# Generated by Django 6.0.6 on 2026-07-30 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_paymentevent_plan_companyinvitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=180, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('WARNING', 'Atenção'), ('CRITICAL', 'Crítico')], max_length=12)),
                ('message', models.CharField(max_length=500)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='rescheduled_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='core.agendamento'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='allowed_information',
            field=models.TextField(blank=True, verbose_name='informações permitidas'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='cancellation_rules',
            field=models.TextField(blank=True, verbose_name='regras de cancelamento'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='faq',
            field=models.TextField(blank=True, verbose_name='perguntas frequentes'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='guidance',
            field=models.TextField(blank=True, verbose_name='orientações de atendimento'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='policies',
            field=models.TextField(blank=True, verbose_name='políticas'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='service_rules',
            field=models.TextField(blank=True, verbose_name='regras de atendimento'),
        ),
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(db_index=True, default='default', max_length=40)),
                ('task_name', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('RETRY', 'Nova tentativa'), ('COMPLETED', 'Concluído'), ('DEAD', 'Falha permanente')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['available_at', 'id'],
                'indexes': [models.Index(fields=['queue', 'status', 'available_at'], name='core_asyncj_queue_86b4bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='palavras-chave')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_articles', to='core.empresacliente')),
            ],
            options={
                'ordering': ['category', 'title'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'title'), name='unique_knowledge_title_per_company')],
            },
        ),
        migrations.CreateModel(
            name='OperationalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField(default=1)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_metrics', to='core.empresacliente')),
            ],
            options={
                'indexes': [models.Index(fields=['name', '-recorded_at'], name='core_operat_name_fdc064_idx')],
            },
        ),
    ]
