# Generated by Django 6.0.6 on 2026-07-30 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_operationalalert_agendamento_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_retention_days', models.PositiveIntegerField(default=730)),
                ('attendance_retention_days', models.PositiveIntegerField(default=730)),
                ('anonymize_instead_of_delete', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='core.empresacliente')),
            ],
        ),
        migrations.CreateModel(
            name='MetaOnboardingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_verified', models.BooleanField(default=False)),
                ('outbound_verified', models.BooleanField(default=False)),
                ('tenant_isolation_verified', models.BooleanField(default=False)),
                ('templates_verified', models.BooleanField(default=False)),
                ('permissions_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_verifications', to='core.empresacliente')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_verifications', to='core.whatsappintegration')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_response_id', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(max_length=80)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('tool_calls', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=True)),
                ('error_type', models.CharField(blank=True, max_length=80)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to='core.atendimento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to='core.empresacliente')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', '-created_at'], name='core_aiusag_empresa_0177ac_idx'), models.Index(fields=['empresa', 'succeeded', '-created_at'], name='core_aiusag_empresa_61ae32_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('ACCESS', 'Acesso/exportação'), ('DELETION', 'Exclusão'), ('CORRECTION', 'Correção')], max_length=16)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebida'), ('VERIFYING', 'Verificando identidade'), ('APPROVED', 'Aprovada'), ('COMPLETED', 'Concluída'), ('REJECTED', 'Rejeitada')], default='RECEIVED', max_length=16)),
                ('subject_name', models.CharField(blank=True, max_length=120)),
                ('whatsapp_id', models.CharField(max_length=32)),
                ('verification_notes', models.TextField(blank=True)),
                ('legal_basis_for_retention', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests', to='core.contato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_subject_requests', to='core.empresacliente')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['empresa', 'status', '-requested_at'], name='core_datasu_empresa_32c6b6_idx')],
            },
        ),
    ]
