# Generated by Django 6.0.6 on 2026-08-01 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aipromptprofile_whatsappsession_whatsappsessionevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aipromptprofile',
            name='autosaved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aipromptprofile',
            name='draft_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='attachment',
            field=models.FileField(blank=True, upload_to='knowledge/%Y/%m/', verbose_name='arquivo'),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='content_type',
            field=models.CharField(choices=[('FAQ', 'FAQ'), ('PRODUCT', 'Produto'), ('SERVICE', 'Serviço'), ('PRICE', 'Valor'), ('DOCUMENT', 'Documento'), ('POLICY', 'Política')], default='FAQ', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor'),
        ),
        migrations.CreateModel(
            name='AttendanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attendances/%Y/%m/')),
                ('media_type', models.CharField(default='document', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.atendimento')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='core.atendimento')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='core.empresacliente')),
            ],
            options={
                'ordering': ['-is_system', 'name'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'name'), name='unique_prompt_template_per_company')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(default='#00e5ff', max_length=7)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_tags', to='core.empresacliente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'name'), name='unique_attendance_tag_per_company')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('blocks_schedule', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.empresacliente')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'date'), name='unique_holiday_per_company')],
            },
        ),
    ]
