# Generated by Django 6.0.6 on 2026-08-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aipromptprofile_autosaved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetag',
            name='attendances',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.atendimento'),
        ),
    ]
