# Generated by Django 6.0.6 on 2026-08-01 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_apirefreshtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['empresa', 'status', '-last_message_at'], name='core_atendi_empresa_e070e8_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['empresa', 'current_step', '-last_message_at'], name='core_atendi_empresa_a771bd_idx'),
        ),
    ]
