# Generated by Django 6.0.6 on 2026-08-03 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ignoredphonenumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome da base')),
                ('data_type', models.CharField(choices=[('PRODUCT', 'Produtos e estoque'), ('SERVICE', 'Serviços e valores'), ('ORDER', 'Pedidos e ordens de serviço'), ('PROPERTY', 'Imóveis'), ('CASE', 'Casos e processos'), ('OTHER', 'Outros dados')], max_length=16, verbose_name='tipo de dados')),
                ('source_filename', models.CharField(max_length=255, verbose_name='arquivo de origem')),
                ('columns', models.JSONField(default=list, verbose_name='colunas importadas')),
                ('ai_visible_columns', models.JSONField(default=list, verbose_name='colunas permitidas para a IA')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='registros importados')),
                ('is_active', models.BooleanField(default=True, verbose_name='disponível para a IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_data_sources', to='core.empresacliente')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_data_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('searchable_text', models.TextField(blank=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_data_records', to='core.empresacliente')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.businessdatasource')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessdatasource',
            constraint=models.UniqueConstraint(fields=('empresa', 'name'), name='unique_business_source_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='businessdatarecord',
            index=models.Index(fields=['empresa', 'source'], name='core_busine_empresa_9fe6f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessdatarecord',
            constraint=models.UniqueConstraint(fields=('source', 'row_number'), name='unique_business_record_row'),
        ),
    ]
