# Generated by Django 6.0.6 on 2026-08-04 19:58

import hashlib

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def initialize_active_prompt_versions(apps, schema_editor):
    Profile = apps.get_model('core', 'AIPromptProfile')
    Version = apps.get_model('core', 'AIPromptVersion')

    for profile in Profile.objects.all().iterator():
        for version in Version.objects.filter(profile_id=profile.pk):
            version.content_hash = hashlib.sha256(version.content.encode('utf-8')).hexdigest()
            version.save(update_fields=['content_hash'])

        active_content = profile.generated_prompt or ''
        if active_content.strip():
            active = Version.objects.filter(
                profile_id=profile.pk, content=active_content,
            ).order_by('-version').first()
            if active is None:
                last = Version.objects.filter(profile_id=profile.pk).order_by('-version').first()
                active = Version.objects.create(
                    profile_id=profile.pk,
                    version=(last.version if last else 0) + 1,
                    content=active_content,
                    content_hash=hashlib.sha256(active_content.encode('utf-8')).hexdigest(),
                    created_by_id=profile.empresa.usuario_id,
                )
            active.is_active = True
            active.published_at = active.created_at or timezone.now()
            active.save(update_fields=['is_active', 'published_at'])

def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_businessdatasource_businessdatarecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aipromptversion',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aipromptversion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='aipromptversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(initialize_active_prompt_versions, noop_reverse),
        migrations.AddConstraint(
            model_name='aipromptversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('profile',), name='unique_active_ai_prompt_version_per_profile'),
        ),
    ]
