# Generated by Django 6.0.6 on 2026-08-05 19:27

import django.db.models.deletion
from django.db import migrations, models
from datetime import timedelta
from uuid import NAMESPACE_URL, uuid5


def backfill_checkout_attempts(apps, schema_editor):
    AuditEvent = apps.get_model('core', 'AuditEvent')
    Attempt = apps.get_model('core', 'BillingCheckoutAttempt')
    Subscription = apps.get_model('core', 'Subscription')
    definitions = {
        'monthly': (14700, 'MONTHLY'),
        'annual': (99700, 'YEARLY'),
    }
    for audit in AuditEvent.objects.filter(action__in=['billing.checkout_requested', 'billing.checkout_reused']):
        metadata = audit.metadata or {}
        checkout_id = str(metadata.get('checkout_id') or '')
        plan_code = str(metadata.get('plan_code') or '')
        if not checkout_id or plan_code not in definitions or not audit.empresa_id:
            continue
        subscription = Subscription.objects.filter(empresa_id=audit.empresa_id, provider='ASAAS').first()
        if not subscription:
            continue
        amount_cents, cycle = definitions[plan_code]
        attempt_uuid = uuid5(NAMESPACE_URL, f'iaatende:asaas:checkout:{checkout_id}')
        attempt, created = Attempt.objects.get_or_create(
            provider_checkout_id=checkout_id,
            defaults={
                'empresa_id': audit.empresa_id,
                'subscription_id': subscription.pk,
                'provider': 'ASAAS',
                'external_reference': (
                    f'iaatende:company:{subscription.billing_reference}:'
                    f'plan:{plan_code}:attempt:{attempt_uuid}'
                ),
                'plan_code': plan_code,
                'amount_cents': amount_cents,
                'cycle': cycle,
                'expires_at': audit.created_at + timedelta(minutes=60),
            },
        )
        if created:
            Attempt.objects.filter(pk=attempt.pk).update(created_at=audit.created_at, updated_at=audit.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_auditevent_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ASAAS', max_length=20)),
                ('provider_checkout_id', models.CharField(max_length=120, unique=True)),
                ('external_reference', models.CharField(max_length=240, unique=True)),
                ('plan_code', models.SlugField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('cycle', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('ABANDONED', 'Abandonado')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_checkout_attempts', to='core.empresacliente')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_attempts', to='core.subscription')),
            ],
        ),
        migrations.RunPython(backfill_checkout_attempts, migrations.RunPython.noop),
    ]
