# Generated by Django 6.0.6 on 2026-08-06 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_billingcheckoutattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('GENERATING', 'Gerando'), ('GENERATED', 'Gerada'), ('AMBIGUOUS', 'Resultado ambíguo'), ('FAILED', 'Falhou'), ('SENT', 'Enviada')], default='GENERATING', max_length=16)),
                ('response_text', models.TextField(blank=True)),
                ('provider_response_id', models.CharField(blank=True, max_length=120)),
                ('quota_consumed', models.BooleanField(default=False)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_message_id', models.CharField(max_length=255, unique=True)),
                ('contact_identifier', models.CharField(blank=True, max_length=64)),
                ('message_type', models.CharField(default='unknown', max_length=32)),
                ('reason', models.CharField(default='subscription_blocked', max_length=80)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='conversation_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='asyncjob',
            index=models.Index(fields=['conversation_key', 'status', 'created_at'], name='core_asyncj_convers_aa9951_idx'),
        ),
        migrations.AddField(
            model_name='airesponsedraft',
            name='atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_drafts', to='core.atendimento'),
        ),
        migrations.AddField(
            model_name='airesponsedraft',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_drafts', to='core.empresacliente'),
        ),
        migrations.AddField(
            model_name='airesponsedraft',
            name='inbound_message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_draft', to='core.mensagem'),
        ),
        migrations.AddField(
            model_name='blockedinboundmessage',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_inbound_messages', to='core.empresacliente'),
        ),
        migrations.AddIndex(
            model_name='airesponsedraft',
            index=models.Index(fields=['empresa', 'status', '-created_at'], name='core_airesp_empresa_909903_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedinboundmessage',
            index=models.Index(fields=['empresa', '-received_at'], name='core_blocke_empresa_6cb248_idx'),
        ),
    ]
