from django.urls import path

from . import views
from .webhook_views import whatsapp_webhook
from .presentation import module_views
from .presentation import security_views


urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('onboarding/', views.onboarding, name='onboarding'),
    path('equipe/', views.equipe, name='equipe'),
    path('equipe/<int:membership_id>/status/', views.membro_status, name='membro_status'),
    path('convites/<str:token>/aceitar/', views.aceitar_convite, name='aceitar_convite'),
    path('planos/', views.planos, name='planos'),
    path('planos/<int:plan_id>/checkout/', views.iniciar_checkout, name='iniciar_checkout'),
    path('webhooks/stripe/', views.stripe_webhook, name='stripe_webhook'),
    path('agenda/lembretes/', views.lembretes_configuracao, name='lembretes_configuracao'),
    path('politica-de-privacidade/', views.politica_privacidade, name='politica_privacidade'),
    path('termos-de-servico/', views.termos_servico, name='termos_servico'),
    path('exclusao-de-dados/', views.exclusao_dados, name='exclusao_dados'),
    path('painel/', views.dashboard, name='dashboard'),
    path('atendimentos/', views.atendimentos, name='atendimentos'),
    path('atendimentos/<int:atendimento_id>/', views.atendimento_detalhe, name='atendimento_detalhe'),
    path('atendimentos/<int:atendimento_id>/assumir/', views.assumir_atendimento, name='assumir_atendimento'),
    path('atendimentos/<int:atendimento_id>/mensagens/enviar/', views.enviar_mensagem_atendimento, name='enviar_mensagem_atendimento'),
    path('atendimentos/<int:atendimento_id>/devolver-ia/', views.devolver_atendimento_ia, name='devolver_atendimento_ia'),
    path('atendimentos/<int:atendimento_id>/finalizar/', views.finalizar_atendimento, name='finalizar_atendimento'),
    path('atendimentos/<int:atendimento_id>/eventos/', views.atendimento_eventos, name='atendimento_eventos'),
    path('atendimentos/eventos/', views.inbox_eventos, name='inbox_eventos'),
    path('atendimentos/<int:atendimento_id>/status/', views.atualizar_status_atendimento, name='atualizar_status_atendimento'),
    path('atendimentos/<int:atendimento_id>/avisar-whatsapp/', views.avisar_whatsapp_atendimento, name='avisar_whatsapp_atendimento'),
    path('minha-empresa/', views.minha_empresa, name='minha_empresa'),
    path('configuracoes/', views.configuracoes, name='configuracoes'),
    path('conta/trocar-senha/', views.trocar_senha, name='trocar_senha'),
    path('configuracoes/ia/', views.configuracao_ia, name='configuracao_ia'),
    path('configuracoes/base-conhecimento/', views.base_conhecimento, name='base_conhecimento'),
    path('configuracoes/base-conhecimento/<int:article_id>/excluir/', views.base_conhecimento_excluir, name='base_conhecimento_excluir'),
    path('dados-negocio/', views.dados_negocio, name='dados_negocio'),
    path('dados-negocio/<int:source_id>/status/', views.dados_negocio_status, name='dados_negocio_status'),
    path('dados-negocio/<int:source_id>/excluir/', views.dados_negocio_excluir, name='dados_negocio_excluir'),
    path('configuracoes/privacidade/', views.privacidade_dados, name='privacidade_dados'),
    path('configuracoes/privacidade/<int:request_id>/aprovar/', views.privacidade_aprovar, name='privacidade_aprovar'),
    path('configuracoes/privacidade/<int:request_id>/executar/', views.privacidade_executar, name='privacidade_executar'),
    path('configuracoes/privacidade/<int:request_id>/exportar/', views.privacidade_exportar, name='privacidade_exportar'),
    path('configuracoes/whatsapp/conectar/', views.whatsapp_onboarding, name='whatsapp_onboarding'),
    path('configuracoes/whatsapp/producao/', views.meta_producao, name='meta_producao'),
    path('metricas/ia/', views.metricas_ia, name='metricas_ia'),
    path('configuracoes/whatsapp/desconectar/', views.whatsapp_desconectar, name='whatsapp_desconectar'),
    path('configuracoes/testar-whatsapp/', views.testar_integracao_whatsapp, name='testar_integracao_whatsapp'),
    path('agenda/', views.agenda, name='agenda'),
    path('agenda/novo/', views.agendamento_novo, name='agendamento_novo'),
    path('agenda/<int:agendamento_id>/', views.agendamento_detalhe, name='agendamento_detalhe'),
    path('agenda/<int:agendamento_id>/editar/', views.agendamento_editar, name='agendamento_editar'),
    path('agenda/<int:agendamento_id>/status/', views.agendamento_status, name='agendamento_status'),
    path('agenda/configuracao/', views.agenda_configuracao, name='agenda_configuracao'),
    path('agenda/configuracao/<str:tipo>/<int:objeto_id>/excluir/', views.agenda_configuracao_excluir, name='agenda_configuracao_excluir'),
    path('fluxo/', views.fluxo, name='fluxo'),
    path('fluxo/aplicar-template/', views.aplicar_template_fluxo, name='aplicar_template_fluxo'),
    path('atendimento/<slug:public_slug>/', views.atendimento_publico, name='atendimento_publico'),
    path('webhooks/whatsapp/', whatsapp_webhook, name='whatsapp_webhook'),
    path('whatsapp/', module_views.whatsapp_dashboard, name='whatsapp_dashboard'),
    path('whatsapp/acao/<str:action>/', module_views.whatsapp_action, name='whatsapp_action'),
    path('whatsapp/status/', module_views.whatsapp_status, name='whatsapp_status'),
    path('webhooks/evolution/', module_views.evolution_webhook, name='evolution_webhook'),
    path('health/whatsapp/', module_views.whatsapp_health, name='whatsapp_health'),
    path('ia/', module_views.ai_dashboard, name='ai_dashboard'),
    path('ia/prompt/gerar/', module_views.prompt_generator, name='prompt_generator'),
    path('ia/prompt/editor/', module_views.prompt_editor, name='prompt_editor'),
    path('ia/prompt/editor/exportar/', module_views.prompt_export, name='prompt_export'),
    path('ia/prompt/versoes/<int:version_id>/restaurar/', module_views.prompt_restore, name='prompt_restore'),
    path('ia/prompt/editor/autosave/', module_views.prompt_autosave, name='prompt_autosave'),
    path('ia/prompt/versoes/<int:version_id>/duplicar/', module_views.prompt_duplicate, name='prompt_duplicate'),
    path('ia/prompt/versoes/comparar/', module_views.prompt_diff, name='prompt_diff'),
    path('numeros-pass/', module_views.ignored_numbers, name='ignored_numbers'),
    path('numeros-pass/<int:number_id>/excluir/', module_views.ignored_number_delete, name='ignored_number_delete'),
    path('agenda/feriados/novo/', module_views.holiday_create, name='holiday_create'),
    path('conversas/', module_views.conversations_crm, name='conversations_crm'),
    path('conversas/<int:atendimento_id>/exportar/', module_views.conversation_export, name='conversation_export'),
    path('conversas/<int:atendimento_id>/excluir/', module_views.conversation_delete, name='conversation_delete'),
    path('conversas/<int:atendimento_id>/nota/', module_views.conversation_note, name='conversation_note'),
    path('conversas/<int:atendimento_id>/arquivo/', module_views.conversation_attachment, name='conversation_attachment'),
    path('conversas/<int:atendimento_id>/reabrir/', module_views.conversation_reopen, name='conversation_reopen'),
    path('conversas/<int:atendimento_id>/etiqueta/', module_views.conversation_tag, name='conversation_tag'),
    path('dashboard/analytics/', module_views.analytics_dashboard, name='analytics_dashboard'),
    path('dashboard/exportar/', module_views.analytics_export, name='analytics_export'),
    path('seguranca/', security_views.security_center, name='security_center'),
    path('seguranca/tokens/revogar/', security_views.revoke_api_tokens, name='revoke_api_tokens'),
    path('seguranca/sessoes/revogar/', security_views.revoke_other_sessions, name='revoke_other_sessions'),
    path('api/auth/token/', security_views.token_create, name='api_token_create'),
    path('api/auth/refresh/', security_views.token_refresh, name='api_token_refresh'),
    path('api/me/', security_views.api_me, name='api_me'),
]
