"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from decimal import Decimal
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from .email_settings import resolve_email_backend

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env(path):
    """Carrega .env local sem substituir variáveis definidas pelo ambiente."""
    if not path.exists():
        return
    values = {}
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    override = values.get('LOCAL_ENV_OVERRIDE', '').lower() in {'1', 'true', 'yes', 'on'}
    for key, value in values.items():
        if override:
            os.environ[key] = value
        else:
            os.environ.setdefault(key, value)


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


if os.environ.get('APP_ENV', 'development').strip().lower() != 'production':
    load_local_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.environ.get('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-development-only-change-me'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY é obrigatória quando DEBUG=False.')

APP_ENV = os.environ.get('APP_ENV', 'development').strip().lower()
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', 'http://127.0.0.1:8000').rstrip('/')
SITE_URL = os.environ.get('SITE_URL', PUBLIC_BASE_URL).rstrip('/')
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '127.0.0.1,localhost,testserver')
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'core',
    'platform_panel',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.RateLimitMiddleware',
    'core.middleware.SubscriptionAccessMiddleware',
    'core.access.RolePermissionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.system_header',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_NAME', BASE_DIR / 'db.sqlite3'),
        'OPTIONS': {'timeout': 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'prompt_generator'
LOGOUT_REDIRECT_URL = 'login'

IAATENDE_WHATSAPP = ''.join(
    character for character in os.environ.get('IAATENDE_WHATSAPP', '')
    if character.isdigit()
)

WHATSAPP_PROVIDER = os.environ.get('WHATSAPP_PROVIDER', 'wa.me')

META_VERIFY_TOKEN = os.environ.get('META_VERIFY_TOKEN', '')
META_APP_SECRET = os.environ.get('META_APP_SECRET', '')
META_APP_ID = os.environ.get('META_APP_ID', '')
META_EMBEDDED_SIGNUP_CONFIG_ID = os.environ.get('META_EMBEDDED_SIGNUP_CONFIG_ID', '')
META_GRAPH_API_VERSION = os.environ.get('META_GRAPH_API_VERSION', 'v23.0')
# Apenas para desenvolvimento com uma única conta de teste. Não é persistido
# nem exibido e deverá ser substituído por cofre/criptografia no multiempresa.
META_ACCESS_TOKEN = os.environ.get('META_ACCESS_TOKEN', '')
WHATSAPP_TOKEN_ENCRYPTION_KEY = os.environ.get('WHATSAPP_TOKEN_ENCRYPTION_KEY', '')
WHATSAPP_WEBHOOK_MAX_BYTES = int(os.environ.get('WHATSAPP_WEBHOOK_MAX_BYTES', 1_048_576))
DATA_UPLOAD_MAX_MEMORY_SIZE = WHATSAPP_WEBHOOK_MAX_BYTES

OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '').strip()
AI_ENABLED = os.environ.get('AI_ENABLED', 'False').lower() in {'1', 'true', 'yes', 'on'}
AI_MODEL = os.environ.get('AI_MODEL', 'gpt-5.6').strip()
AI_TIMEOUT = float(os.environ.get('AI_TIMEOUT', '20'))
AI_AUDIO_TRANSCRIPTION_ENABLED = os.environ.get(
    'AI_AUDIO_TRANSCRIPTION_ENABLED', 'False',
).lower() in {'1', 'true', 'yes', 'on'}
AI_AUDIO_TRANSCRIPTION_MODEL = os.environ.get(
    'AI_AUDIO_TRANSCRIPTION_MODEL', 'gpt-transcribe',
).strip()
AI_AUDIO_MAX_BYTES = int(os.environ.get('AI_AUDIO_MAX_BYTES', str(20 * 1024 * 1024)))
AI_AUDIO_CONVERSION_TIMEOUT = int(os.environ.get('AI_AUDIO_CONVERSION_TIMEOUT', '30'))
AI_CONTEXT_MESSAGE_LIMIT = int(os.environ.get('AI_CONTEXT_MESSAGE_LIMIT', '12'))
AI_CONTEXT_SUMMARY_TRIGGER = int(os.environ.get('AI_CONTEXT_SUMMARY_TRIGGER', '20'))
AI_CONTEXT_SUMMARY_MAX_CHARS = int(os.environ.get('AI_CONTEXT_SUMMARY_MAX_CHARS', '2000'))
AI_INPUT_COST_PER_MILLION = Decimal(os.environ.get('AI_INPUT_COST_PER_MILLION', '0'))
AI_OUTPUT_COST_PER_MILLION = Decimal(os.environ.get('AI_OUTPUT_COST_PER_MILLION', '0'))

ASAAS_ENVIRONMENT = os.environ.get('ASAAS_ENVIRONMENT', 'sandbox').strip().lower()
ASAAS_API_URL = os.environ.get('ASAAS_API_URL', 'https://api-sandbox.asaas.com/v3').rstrip('/')
ASAAS_API_KEY = os.environ.get('ASAAS_API_KEY', '').strip()
ASAAS_WEBHOOK_TOKEN = os.environ.get('ASAAS_WEBHOOK_TOKEN', '').strip()
ASAAS_CHECKOUT_SUCCESS_URL = os.environ.get('ASAAS_CHECKOUT_SUCCESS_URL', '').strip()
ASAAS_CHECKOUT_CANCEL_URL = os.environ.get('ASAAS_CHECKOUT_CANCEL_URL', '').strip()
ASAAS_CHECKOUT_EXPIRES_IN = int(os.environ.get('ASAAS_CHECKOUT_EXPIRES_IN', '60'))
TRIAL_DAYS = 3
SUBSCRIPTION_ENFORCEMENT_ENABLED = False if 'test' in sys.argv else os.environ.get(
    'SUBSCRIPTION_ENFORCEMENT_ENABLED', 'true',
).lower() in {'1', 'true', 'yes', 'on'}
TASK_QUEUE_BACKOFF = int(os.environ.get('TASK_QUEUE_BACKOFF', '30'))
TASK_QUEUE_MAX_BACKOFF = int(os.environ.get('TASK_QUEUE_MAX_BACKOFF', '3600'))
TASK_QUEUE_LEASE_SECONDS = int(os.environ.get('TASK_QUEUE_LEASE_SECONDS', '300'))
TASK_QUEUE_IDLE_SECONDS = float(os.environ.get('TASK_QUEUE_IDLE_SECONDS', '1'))
TASK_QUEUE_HEARTBEAT_SECONDS = int(os.environ.get('TASK_QUEUE_HEARTBEAT_SECONDS', '30'))
TASK_QUEUE_BACKLOG_WARNING_COUNT = int(os.environ.get('TASK_QUEUE_BACKLOG_WARNING_COUNT', '20'))
TASK_QUEUE_BACKLOG_MAX_AGE_SECONDS = int(os.environ.get('TASK_QUEUE_BACKLOG_MAX_AGE_SECONDS', '60'))
OPERATIONAL_ALERT_WEBHOOK = os.environ.get('OPERATIONAL_ALERT_WEBHOOK', '')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'whatsapp': {
            'format': '{levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'whatsapp',
        },
    },
    'loggers': {
        'whatsapp': {
            'handlers': ['console'],
            'level': os.environ.get('WHATSAPP_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# E-mail: ativa SMTP somente quando a configuração completa estiver presente.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').strip()
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in {'1', 'true', 'yes', 'on'}
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in {'1', 'true', 'yes', 'on'}
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'IAATENDE 2.0 <nao-responda@localhost>').strip()
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', '3600'))
EMAIL_BACKEND = resolve_email_backend(os.environ)

EVOLUTION_API_URL = os.environ.get('EVOLUTION_API_URL', '')
EVOLUTION_API_KEY = os.environ.get('EVOLUTION_API_KEY', '')
EVOLUTION_WEBHOOK_SECRET = os.environ.get('EVOLUTION_WEBHOOK_SECRET', '')
EVOLUTION_WEBHOOK_URL = os.environ.get('EVOLUTION_WEBHOOK_URL', '').strip()
JWT_ACCESS_SECONDS = int(os.environ.get('JWT_ACCESS_SECONDS', '900'))
JWT_REFRESH_SECONDS = int(os.environ.get('JWT_REFRESH_SECONDS', '604800'))
APP_VERSION = os.environ.get('APP_VERSION', 'development')
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 'LOCATION': 'iaatende-runtime'}}
